import assert from 'node:assert/strict';
import {mkdir,readFile} from 'node:fs/promises';
import {chromium} from 'playwright';
const origin=process.env.BROWSER_APP_URL||'http://127.0.0.1:8765';
let ready=false;
for(let attempt=0;attempt<20;attempt++){
  try {const response=await fetch(origin);if(response.ok){ready=true;break;}}catch{}
  await new Promise(resolve=>setTimeout(resolve,500));
}
assert.equal(ready,true,'Browser site did not become ready');
const browser=await chromium.launch();
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await context.newPage();
const errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('request',r=>requests.push(new URL(r.url()).pathname));
page.on('dialog',dialog=>dialog.accept());
try {
  await page.goto(origin,{waitUntil:'networkidle'});
  await page.getByRole('button',{name:'+ Add application',exact:true}).click();
  await page.getByLabel('Company',{exact:true}).fill('Release Company');
  await page.getByLabel('Role',{exact:true}).fill('Python intern');
  await page.getByLabel('Notes',{exact:true}).fill('=1+1');
  await page.getByRole('button',{name:'Save application',exact:true}).click();
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.locator('#stat-total').textContent(),'1');
  assert.equal(await page.locator('.company').textContent(),'Release Company');
  await page.getByRole('button',{name:'Try sample board',exact:true}).click();
  assert.equal(await page.locator('#stat-total').textContent(),'5');
  await page.getByRole('button',{name:'My board',exact:true}).click();
  assert.equal(await page.locator('#stat-total').textContent(),'1');
  await page.getByRole('button',{name:'Edit Python intern at Release Company',exact:true}).click();
  await page.getByLabel('Stage',{exact:true}).selectOption('Interview');
  await page.getByRole('button',{name:'Save application',exact:true}).click();
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.locator('#stat-interview').textContent(),'1');
  const csvEvent=page.waitForEvent('download');
  await page.getByRole('button',{name:'Export CSV ↓',exact:true}).click();
  const csv=await csvEvent;
  assert.match(await readFile(await csv.path(),'utf8'),/"'=1\+1"/);
  const backupEvent=page.waitForEvent('download');
  await page.getByRole('button',{name:'Backup JSON ↓',exact:true}).click();
  const backup=await backupEvent;
  assert.equal(JSON.parse(await readFile(await backup.path(),'utf8')).applications.length,1);
  await page.getByRole('button',{name:'Edit Python intern at Release Company',exact:true}).click();
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  assert.equal(await page.locator('#stat-total').textContent(),'0');
  await page.locator('#restore-file').setInputFiles(await backup.path());
  await page.waitForFunction(()=>document.querySelector('#stat-total').textContent==='1');
  await page.locator('#restore-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":1,"applications":[{"company":"broken"}]}')});
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.startsWith('Restore failed:'));
  assert.equal(await page.locator('#stat-total').textContent(),'1');
  await page.locator('#search').fill('nothing-matches-this');
  assert.equal(await page.locator('.application').count(),0);
  await page.locator('#search').fill('');
  await page.locator('#filter').selectOption('Saved');
  assert.equal(await page.locator('.application').count(),0);
  await page.locator('#filter').selectOption('');
  await page.getByRole('button',{name:'+ Add application',exact:true}).click();
  await page.getByLabel('Company',{exact:true}).fill('<img src=x onerror=alert(1)>');
  await page.getByLabel('Role',{exact:true}).fill('Text rendering check');
  await page.getByRole('button',{name:'Save application',exact:true}).click();
  assert.equal(await page.locator('#board img').count(),0);
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.locator('#stat-total').textContent(),'2');
  await mkdir('browser-qa',{recursive:true});
  await page.screenshot({path:'browser-qa/desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'browser-qa/mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  const isolated=await browser.newContext();
  const separate=await isolated.newPage();
  await separate.goto(origin,{waitUntil:'networkidle'});
  assert.equal(await separate.locator('#stat-total').textContent(),'0');
  await isolated.close();
  assert.equal(requests.some(path=>path.startsWith('/api/')),false);
  assert.deepEqual(errors,[]);
  console.log('PASS: saved create/edit/delete/reload, sample isolation, JSON backup/restore and rejection, CSV safety, filters, safe text rendering, device isolation and mobile layout.');
} finally {await browser.close();}
